# Generated by Django 3.2.4 on 2021-11-16 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20211116_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semister',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
