# Generated by Django 3.0.7 on 2021-11-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_semister_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semister',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cradits',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semister',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Semister',
        ),
    ]
